main: com.cavetale.chess.ChessPlugin
name: Chess

version: ${version}
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Chess
description: Chess Plugin

depend: [Core, Mytems, Area]
softdepend: []

commands:

  chess:
    aliases: []
    description: Chess Command
    permission: chess.chess
    usage: |-
      /chess

  chessadmin:
    aliases: [chessadm]
    description: Chess Admin Command
    permission: chess.admin
    usage: |-
      /chessadm

permissions:

  chess.chess:
    description: Use /chess
    default: op

  chess.admin:
    description: Use /chessadm
    default: op
